services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
    environment:
      - NODE_ENV=development
    command: live-server --host=0.0.0.0 --port=8080 --no-browser --watch=.
    restart: unless-stopped